[project]
name = "BIDSlab"
dynamic = ["version"]
description = "A Python package for handling BIDS datasets."
authors = [
    { name = "Lukas Behammer", email = "lukas.behammer@uni-a.de" },
]
readme = "README.md"
requires-python = ">=3.12"
keywords = [
    "BIDS",
    "neuroimaging",
    "data management",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
]
license = "BSD-3-Clause"
license-files = ["LICENSE.txt"]
dependencies = [
    "uritools",
    "pandas",
    "edf_reader",
]

[project.optional-dependencies]
datalad = [
    "datalad",
]

[project.urls]
Repository = "https://github.com/cimt-unia/bidslab"
#Homepage
Documentation = "https://bidslab.readthedocs.io/en/latest/"
Changelog = "https://github.com/cimt-unia/bidslab/blob/main/CHANGELOG.md"
Tracker = "https://github.com/cimt-unia/bidslab/issues"
Download = "https://github.com/cimt-unia/bidslab/releases/latest"
Codecov = "https://codecov.io/gh/cimt-unia/bidslab"

[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=9.2"]
build-backend = "setuptools.build_meta"

[dependency-groups]
test = [
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "pytest-sugar",
    "pytest-random-order",
    "pytest-doctestplus",
    "syrupy",
    "mimesis",
    "typing_extensions",
]
docs = [
    "sphinx",
    "sphinx-autobuild",
    "sphinxcontrib-email",
    "sphinx-copybutton",
    "sphinx-last-updated-by-git",
    "pydata-sphinx-theme",
    # These are duplicates of other dependency groups, but sometimes only the docs group
    # is installed and not all dependencies from the other groups are needed.
    "numpydoc",
    "pytest-doctestplus",
]
lint = [
    "ruff",
    "numpydoc",
]
typing = [
    "mypy",
]
build = [
    "build",
    "setuptools",
    "setuptools-scm",
]
release = [
    {include-group = "build"},
    "twine",
    "git-cliff"
]
tox = [
    "tox>=4.49.0",
    "tox-gh-actions",
    "packaging>=26.0"
]
dev = [
    {include-group = "test"},
    {include-group = "docs"},
    {include-group = "typing"},
    {include-group = "lint"},
    {include-group = "release"},
    {include-group = "tox"},
    "pre-commit"
]

######################################################################
# Ruff
[tool.ruff]
extend-exclude = [
    "docs",
    "build",
    "dist",
]
#output-prefer-rule-codes = true  #! Breaks validate pyproject.toml

[tool.ruff.lint]
preview = false  #! Breaks validate pyproject.toml
select = [
    "A",
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "C4",
    "C90",
    "COM",
    "CPY",
    "D",
    "E",
    "F",
    "G",
    "I",
    "ICN",
    "INP",
    "N",
    "PERF",
    "PT",
    "PGH",
    "PTH",
    "Q",
    "RET",
    "RUF",
    "S",
    "SLF",
    "UP",
    "W",
]
ignore = [
    "ANN204",
    "ANN401",
    "B028",
    "COM812",
    "D105",
    "D401", # due to numpydoc SS05 implementing this
    "D206",
    "D300",
#    "D421",  # TODO: Remove  #! Breaks validate pyproject.toml
    "E111",
    "E114",
    "E117",
#    "RUF105",  #! Breaks validate pyproject.toml
#    "RUF106",  #! Breaks validate pyproject.toml
#    "RUF201",  #! Breaks validate pyproject.toml
    "S101",  # TODO: Remove
    "SLF001",
    "W191",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "ANN",
    "ARG001",
    "ARG002",
    "ASYNC",
    "D",
    "RUF029",
    "S101"
]
"tools/generate_requirements.py" = ["CPY001", "D"] # TODO: Remove

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
known-first-party = ["src/bidslab"]

######################################################################
# Numpydoc
[tool.numpydoc_validation]
checks = [
    "all",  # report on all checks, except the below
    "EX01",
    "SA01",
    "ES01",
]
exclude = [  # don't report on objects that match any of these regex
    '\.__repr__$',
    '\.__hash__$',
    '\.__init__$',
    'bidslab._typing.'
]
exclude_files = [ # don't process filepaths that match these regex
    '^tests/.*',
    '^docs/.*',
    '^tools/.*',
]


######################################################################
# MyPy
[tool.mypy]
exclude = [
    "tests",
    "data",
    "docs",
    "build",
    "dist",
    "tools",
    "templates",
    "branding",
    "temp",  # TODO: Remove
]
files = "src/bidslab"
strict = false
pretty = true
disable_error_code = ["import-not-found", "import-untyped"]
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
check_untyped_defs = true
follow_untyped_imports = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = [
    "uritools",
]
ignore_missing_imports = true

######################################################################
# PyTest
[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "-ra --cov --cov-branch --cov-append --cov-report=term-missing --cov-report=xml --import-mode=importlib --random-order --strict-config --strict-markers"
minversion = "9"
xfail_strict = true
log_level = "INFO"
filterwarnings = [
    "error",
]

#######################################################################
# Vulture
[tool.vulture]
make_whitelist = true
min_confidence = 80
paths = ["src"]
sort_by_size = true
verbose = false
